controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
get_products:
    path: /products
    controller: App\Controller\ProductController::getProducts
get_product_by_id:
    path: /products/{id}
    controller: App\Controller\ProductController::getProductById